mathhub/apps/register/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import acc


app_name = 'register'

urlpatterns = [
    path('', login_required(acc), name='acc')
]

mathhub/apps/survey/urls.py
from django.urls import path
from .views import survey_page, save_answers


app_name = 'survey'

urlpatterns = [
    path('what_mathematician_you_are/',
         survey_page, name='survey_page'),
    path('save-answers/', save_answers)
]

mathhub/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import user_login_register


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_login_register, name='main'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('acc/', include('register.urls')),
    path('survey/', include('survey.urls'))
]

mathhub/apps/register/models.py
from django.db import models
from django.contrib.auth.models import User


class LivePlace(models.Model):
    CHOICES = (
        ("Отсутствует", "Отсутствует"),
        ("Кампус", "Кампус"),
        ("Город", "Город"),
        ("Подвал", "Подвал"),
        ("Под мостом", "Под мостом")
    )
    place = models.CharField("Предпочитаемое место жительства",
                             max_length=20, choices=CHOICES)
    

class ChosenIntegral(models.Model):
    CHOICES = (
        (1, "1"),
        (2, "2"),
        (3, "3"),
        (4, "4"),
    )
    integral = models.IntegerField("Выбранные интегралы",
                                   choices=CHOICES)


class ProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_math = models.BooleanField("Математик?")
    live_place = models.ForeignKey(LivePlace, on_delete=models.CASCADE)
    chosen_integrals = models.ManyToManyField(ChosenIntegral)


class Subscription(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

mathhub/apps/survey/models.py
from django.db import models

# Create your models here.

mathhub/apps/register/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from .models import ProfileInfo, LivePlace, ChosenIntegral


@transaction.atomic
def acc(request):
    prof = get_object_or_404(ProfileInfo, user_id=request.user)
    # live_place = get_object_or_404(LivePlace, id=prof.live_place.id)
    integrals = prof.chosen_integrals.all()
    li = len(integrals)
    if li == 1:
        integrals = integrals.first()
    
    return render(request, 'login/auth_success.html',
                  {
                      'is_mathematician': prof.is_math,
                      'place': prof.live_place,
                      'integrals': integrals,
                      'int_count': li
                  })

mathhub/apps/survey/views.py
import json
from collections import Counter
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST


def survey_page(request):
    # if request.method == 'POST':
    #     answers = request.POST.getlist('answers[]')
    #
    #     # Тут можно сохранять ответы в базу данных
    #     # или обрабатывать каким-либо другим способом
    #
    #     # В этом примере мы просто подсчитываем количество
    #     # уникальных ответов
    #     statistics = dict(Counter(answers))
    #
    #     return JsonResponse({'statistics': statistics})
    
    return render(request, 'survey/index.html')


@require_POST
@csrf_exempt
def save_answers(request):
    if request.method == 'POST':
        print('что-то произошло')
        print(repr(request.POST))
        try:
            rp = request.POST
            print('данные загружены')
            answers = [(key[key.index('[') + 1: -1],
                        rp[key][0] if len(rp[key]) == 1 else rp[key])
                       for key in rp if key.startswith('answers[')]
            print('ответы получены')
            
            value = k = 0  # результат игрока и множитель возраста
            personal_stat = []
            rank = 'Дефолтный математический нормис'
            if 0 < int(answers[0][1]) < 18:
                k = 1.5
            elif 18 <= int(answers[0][1]) < 36:
                k = 0.9
            elif 36 <= int(answers[0][1]) < 60:
                k = 1
            elif 60 <= int(answers[0][1]) < 80:
                k = 1.1
            else:
                k = 1.25
            
            if answers[1][1] in ['Алгебра', 'Геометрия']:
                value += 2
                personal_stat.append((answers[1][1],
                                      'Любитель попроще? Понимаю.', 2))
            elif answers[1][1] in ['Матан', 'Линал']:
                value += 4
                personal_stat.append((answers[1][1],
                                      'Нормальная математика пошла. Хорош.', 4))
            elif answers[1][1] in ['Теорвер', 'МатСтат']:
                value += 6
                personal_stat.append((answers[1][1],
                                      'Welcome to the club', 6))
            elif answers[1][1] in ['Диффуры', 'Компан (ТФКП)']:
                value += 8
                personal_stat.append(
                    (answers[1][1], 'А ты любитель острых ощущений', 8))
            elif answers[1][1] in ['Топология', 'Функан', 'Теормех']:
                value += 10
                personal_stat.append((answers[1][1], 'Соболезную', 10))
            
            if int(answers[2][1]) <= 10:
                value -= 10
                personal_stat.append(
                    (answers[1][1],
                     'Меньше 10 секунд!? Кому ты тут сказки '
                     'рассказываешь? В следующий раз либо отвечай '
                     'честно, либо не проходи этот тест больше никогда',
                     -10))
            elif 10 < int(answers[2][1]) < 60:
                value -= 5
                personal_stat.append(
                    (answers[1][1],
                     'Меньше минуты!? Это хотя бы не меньше 10 секунд, '
                     'но тоже невозможно. За то, что ты соврал(-а) '
                     'не так сильно, минус балл будет '
                     'не такой большой.',
                     -5))
            elif 60 <= int(answers[2][1]) < 600:
                value += 10
                personal_stat.append(
                    (answers[1][1],
                     'Вау! Меньше 10 минут на такое уравнение! '
                     'Уже звучит реалистично, потому заслуживает '
                     'уважения.',
                     10))
            elif 600 <= int(answers[2][1]) < 86400:
                value += 6
                personal_stat.append(
                    (answers[1][1],
                     'Ты потратил на решение меньше суток. '
                     'Уже не очень, но всё равно заслуживает '
                     '+ несколько баллов.',
                     6))
            elif 86400 <= int(answers[2][1]) < 2592000:
                value += 3
                personal_stat.append(
                    (answers[1][1],
                     'Меньше месяца на такую задачу? Мда...',
                     3))
            elif 2592000 <= int(answers[2][1]):
                value += 1
                personal_stat.append(
                    (answers[1][1],
                     'Как вообще можно было ввести такое значение? '
                     'Я не знаю. Тестируешь опрос что ли? '
                     'Ладно, держи 1 балл как тестировщик',
                     1))
            
            if answers[3][1] == 'Да':
                value += 10
                personal_stat.append((answers[3][1], 'Правильно', 10))
            elif answers[3][1] == 'Нет':
                value += 2
                personal_stat.append((answers[3][1], 'Неправильно', 2))
            else:
                value += 5
                personal_stat.append((answers[3][1],
                                      '5 очков на подумать.',
                                      5))
                
            if answers[4][1] == '0':
                value += 1
                personal_stat.append((answers[4][1], 'Кринж', 1))
            elif answers[4][1] == '1-3':
                value += 4
                personal_stat.append((answers[4][1],
                                      'Это только начало', 4))
            elif answers[4][1] == '4-10':
                value += 7
                personal_stat.append((answers[4][1],
                                      'Да вы прям знаток матана.', 7))
            elif answers[4][1] == '> 10':
                value += 10
                personal_stat.append(
                    (answers[4][1],
                     'Так много не знает, наверное, даже сам Коши.',
                     10))
            else:
                personal_stat.append(
                    (answers[4][1],
                     'Скоро узнаешь, но всё равно кринж',
                     0))
            
            if answers[5][1] == '?':
                value -= 1
                personal_stat.append((answers[5][1], 'Минус балл', -1))
            elif answers[5][1] == 'Не нашёл':
                value += 2
                personal_stat.append(
                    (answers[5][1],
                     'А теперь найди и больше не теряй',
                     2))
            else:
                value += 10
                personal_stat.append((answers[5][1],
                                      'Молодец',
                                      10))
            
            if answers[6][1] == ('y\' = -1/2 * e^{-x} + 1; '
                                 'y = 1/2 * e^{-x} + x + 2'):
                value += 10
                personal_stat.append(
                    (answers[6][1],
                     'Это абсолютно правильный ответ! '
                     'Возьми с полки пирожок', 10))
            else:
                value += 2
                personal_stat.append(
                    (answers[6][1],
                     'Ответ неправильный, но за попытку '
                     '(или её отсутствие), можно накинуть', 2))
            
            if answers[7][1] in ['e', 'π', 'Φ', 'i', 'Ω']:
                value += 6
                personal_stat.append(
                    (answers[7][1], 'Вполне нормисная константа', 6))
            elif answers[7][1] in ['γ - постоянная Эйлера-Маскерони',
                                   'ζ(3) - постоянная Апери',
                                   'λ - постоянная Голомба — Дикмана']:
                value += 8
                personal_stat.append(
                    (answers[7][1], 'Довольно редкая константа.', 8))
            else:
                value += 10
                personal_stat.append(
                    (answers[7][1], 'А вы ценитель больших чисел', 10))
            
            if answers[8][1] == '0':
                value += 1
                personal_stat.append((answers[8][1], 'Неодобряемо', 1))
            elif answers[8][1] == '1-9':
                value += 3
                personal_stat.append((answers[8][1],
                                      'Прикоснулся к великому', 4))
            elif answers[8][1] == '10-100':
                value += 6
                personal_stat.append((answers[8][1],
                                      'Уважение и хвала воину', 7))
            elif answers[8][1] == '> 100':
                value += 10
                personal_stat.append(
                    (answers[8][1],
                     'Вот бы мужчины вместо года в армии '
                     'год решали Демидовича... '
                     'Это мир был бы прекрасен',
                     10))
            else:
                personal_stat.append(
                    (answers[8][1],
                     'Сборник задач по матанализу. '
                     'Такую базу должен знать каждый математик.',
                     0))
            
            value = round(value * k)
            if value < 10:
                rank = 'Рус'
            elif value < 30:
                rank = 'Человек'
            elif value < 40:
                pass
            elif value < 50:
                rank = 'Жёсткий математик'
            elif value < 65:
                rank = 'Математический Моцарт'
            elif value >= 65:
                rank = 'Ящер'
            
            statistics = [[f'{q} | Ваш ответ: {a}', d, f'Результат: {s}']
                          for (a, d, s), (q, ans)

mathhub/views.py
import json

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User

from .forms import LoginForm, UserRegistrationForm
from register.models import ProfileInfo, LivePlace, ChosenIntegral, \
    Subscription


def user_login_register(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        user_form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # HttpResponceRedirect
                    return HttpResponseRedirect('acc/')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
        
        if user_form.is_valid():
            password = user_form.cleaned_data['password']
            new_user = User.objects.create_user(
                username=user_form.cleaned_data['login'],
                password=password,
                email=user_form.cleaned_data['email'])
            
            live_place = LivePlace(
                place=user_form.cleaned_data['live_place'])
            live_place.save()
            
            # integral = ChosenIntegral(
            #     integral=request.POST['inlineOptions'])
            # integral.save()
            #
            print(user_form.cleaned_data['is_math'])
            profile = ProfileInfo(user=new_user,
                                  is_math=user_form
                                  .cleaned_data['is_math'],
                                  live_place=live_place)
            profile.save()
            for integral in request.POST.getlist('inlineOptions'):
                profile.chosen_integrals.add(
                    ChosenIntegral.objects.get(integral=int(integral)))
            
            login(request, new_user)
            return HttpResponseRedirect('acc/')
            # return render(request, 'index.html',
            #               {
            #                   'new_user': new_user,
            #                   'form': LoginForm(),
            #                   'user_form': UserRegistrationForm()
            #               }
        
        if ('HTTP_X_REQUESTED_WITH' in request.META
            and request.META['HTTP_X_REQUESTED_WITH']
                == 'XMLHttpRequest'):
            email = request.POST.get('email')
            
            if email:  # Проверка наличия email
                subscriber, created = (Subscription.objects
                                       .get_or_create(email=email))
                
                if created:
                    return JsonResponse(
                        {'message': 'Спасибо за подписку!'})
                else:
                    return JsonResponse(
                        {'message': 'Вы уже подписаны.'})
            else:
                return JsonResponse(
                    {'message': 'Пожалуйста, введите email.'})
        else:
            return JsonResponse({'message': 'Ошибка запроса.'})
    else:
        form = LoginForm()
        user_form = UserRegistrationForm()
    
    return render(request, 'index.html',
                  {'form': form, 'user_form': user_form})

mathhub/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block meta %}{% endblock %}

    {% block link %}{% endblock %}
    <title>{% block title %}Совет молодых учёных ДВО РАН{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

mathhub/templates/basefooter.html
{% load static %}
<hr>
<div>
    <footer>
        <div class="container-fluid row">
            <ul class="nav justify-content-center">
                <li style="margin-bottom: 1em;;"><a href="#" class="nav-link text-info">О нас</a></li>
                <li id="form-li">
                    <form class="d-flex justify-content-start" id="subscriptionForm" method="post">
                        {% csrf_token %}
                        <input type="email" id="emailInput" class="form-control me-2" name="email" placeholder="Введите ваш email" aria-label="Введите ваш email" required style="display: inherit;">
                        <button class="btn btn-outline-danger" type="submit" aria-expanded="true" style="display: inherit;">Оформить подписку</button>
                    </form>
<!--                    <div id="subscriptionMessage" style="display: none;"></div>-->
                </li>
            </ul>
        </div>
    </footer>
    <script src="{% static 'js/subscription.js' %}"></script>
</div>

mathhub/templates/basenavbar.html
{% load static %}
<script>
    // alert('Вау, ты нашёл этот сайт! Поздравляю, у тебя нет личной жизни.');
    console.log('Вау, ты нашёл этот сайт! Поздравляю, у тебя нет личной жизни.');
    let wat = 'Цу сфт кузуфе ше!';
    console.log(wat);
</script>
<header>
    <!-- Навигационная панель -->
    <nav class="navbar navbar-expand-lg navbar navbar-expand-md navbar navbar-expand-sm navbar navbar-expand-xs sticky-top" data-bs-theme="dark">
        <div class="container-fluid justify-content-between">
            <a class="navbar-brand" href="{% url 'main' %}"><img src="{% static 'bsimg/mathhub.jpg' %}"></a>
            <div class="navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0 me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'main' %}">Главная</a>
                    </li>
                    <!-- Выпадающий список -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                            Разделы
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Математический анализ</a></li>
                            <li><a class="dropdown-item" href="#">Линейная алгебра</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Поверхностные интегралы</a></li>
                            <li><a class="dropdown-item" href="#">Линейные пространства</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Другое</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://github.com/Tyferse/websheet/tree/dz7btstrp">GitHub</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#form-li" id="sub-link">Оформить подписку</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'survey:survey_page' %}">Пройти опрос</a>
                    </li>
                </ul>
                <form class="d-flex justify-content-start" role="search">
                    <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Поиск">
                    <button class="btn btn-outline-primary" type="submit" aria-expanded="true">Поиск</button>
                </form>

                <!-- Модальное окно для входа или регистрации -->
                {% if not user.is_authenticated %}
                    <button class="btn btn-warning me-3" data-bs-toggle="modal" data-bs-target="#modal-sign-in" aria-expanded="true" id="loginbtn" style="margin-left: auto;">
                        Войти
                    </button>
                {% else %}
                    <a href="{% url 'register:acc' %}" type="button" class="btn btn-secondary" aria-expanded="true" style="margin: 0.4em 0.8em 0 auto;">
                        Профиль
                    </a>
                    <a href="{% url 'logout' %}?next={% url 'main' %}" type="button" class="btn btn-danger" aria-expanded="true" id="loginbtn">
                        Выйти
                    </a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>